# Generated by Django 4.0.4 on 2022-06-20 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за 1000 шт.')),
                ('max_uses', models.IntegerField(default=1, verbose_name='Максимальное кол-во гошений')),
                ('current_uses', models.IntegerField(default=0, verbose_name='Кол-во гошений')),
                ('multi_use', models.BooleanField(help_text='Можно использовать много раз, разными клиентами', verbose_name='Мнократное использование')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_end', models.DateTimeField(null=True, verbose_name='Дата окончания')),
                ('date_use', models.DateTimeField(auto_now=True, verbose_name='Дата последнего гошения')),
                ('is_stop', models.BooleanField(default=False, verbose_name='Использован')),
                ('users', models.ManyToManyField(related_name='cupons', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
