# Generated by Django 4.0.4 on 2022-06-20 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='bonus',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Бонус'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='users',
            field=models.ManyToManyField(null=True, related_name='cupons', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
