# Generated by Django 4.0.4 on 2022-06-20 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cupons', '0002_alter_cupon_bonus_alter_cupon_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='users',
            field=models.ManyToManyField(related_name='cupons', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
