# Generated by Django 4.0.4 on 2022-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0004_cupon_code_alter_cupon_date_end_alter_cupon_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='code',
            field=models.CharField(max_length=7, unique=True, verbose_name='Код'),
        ),
    ]
