# Generated by Django 4.0.4 on 2022-06-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0005_alter_cupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='is_stop',
        ),
    ]
