# Generated by Django 4.0.4 on 2022-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0006_remove_cupon_is_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='owner_id',
            field=models.IntegerField(blank=True, help_text='ID для кого предназначен купон', null=True, verbose_name='ID владельца'),
        ),
    ]
