# Generated by Django 4.0.4 on 2022-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0007_cupon_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='owner_id',
            field=models.IntegerField(blank=True, help_text='4000+ID для кого предназначен купон', null=True, verbose_name='ID владельца'),
        ),
    ]
