# Generated by Django 4.0.4 on 2022-06-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_provider', models.CharField(choices=[('FREC', 'FreeCassa'), ('YOOM', 'Yoommany')], max_length=4, verbose_name='Вариант оплаты')),
                ('sign', models.UUIDField(null=True)),
                ('pay_url', models.URLField(null=True, verbose_name='Адрес оплаты')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_paid', models.DateTimeField(null=True, verbose_name='Дата оплаты')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='my_site.order', verbose_name='Транзакция')),
            ],
        ),
    ]
