# Generated by Django 4.0.4 on 2022-06-14 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_site', '0005_alter_category_img_alter_subcategory_img'),
        ('payments', '0002_alter_transaction_order_alter_transaction_pay_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_type',
            field=models.CharField(choices=[('LK', 'Профиль'), ('OR', 'Заказ')], default='OR', max_length=2, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='my_site.order', verbose_name='Заказ'),
        ),
    ]
