# Generated by Django 4.0.4 on 2022-06-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_client_transaction_pay_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pay_provider',
            field=models.CharField(choices=[('FREC', 'FreeCassa'), ('YOOM', 'Yoommany'), ('PRF', 'Баланс')], max_length=4, verbose_name='Вариант оплаты'),
        ),
    ]
