# Generated by Django 4.0.4 on 2022-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_pay_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unic_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('LK', 'Профиль'), ('OR', 'Заказ')], default='OR', help_text='Если оплата за заказ, то указывает откуда была оплата, платёжка или баланс.', max_length=2, null=True, verbose_name='Тип оплаты'),
        ),
    ]
