# Generated by Django 4.0.4 on 2022-06-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_unic_id_alter_transaction_pay_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unic_id',
            field=models.IntegerField(default=123, primary_key=True, serialize=False, unique=True, verbose_name='ID транзакции'),
            preserve_default=False,
        ),
    ]
