# Generated by Django 4.0.4 on 2022-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_transaction_id_alter_transaction_unic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
