# Generated by Django 4.0.4 on 2022-06-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_service_quality_service_speed_service_text_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='text_info',
            field=models.TextField(max_length=250, verbose_name='Инфо'),
        ),
    ]
