# Generated by Django 4.0.4 on 2022-06-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_alter_service_text_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='text_info',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Инфо'),
        ),
    ]
