# Generated by Django 4.0.4 on 2022-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_alter_service_text_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.CharField(choices=[('TEL', 'telegram.svg'), ('VK', 'vk.svg'), ('TIK', 'tiktok.svg'), ('INST', 'instagram.svg'), ('CLIN', 'c_link.svg'), ('STAR', 'c_star.svg'), ('EYE', 'eye.svg'), ('HEAR', 'heart.svg'), ('IGTV', 'igtv.svg'), ('LIKE', 'likee.svg'), ('REVO', 'record_voice.svg'), ('SAVE', 'save.svg'), ('SHOW', 'show.svg'), ('THUP', 'thumb-up.svg'), ('USER', 'user.svg'), ('USES', 'users.svg')], max_length=4, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='img',
            field=models.CharField(blank=True, choices=[('TEL', 'telegram.svg'), ('VK', 'vk.svg'), ('TIK', 'tiktok.svg'), ('INST', 'instagram.svg'), ('CLIN', 'c_link.svg'), ('STAR', 'c_star.svg'), ('EYE', 'eye.svg'), ('HEAR', 'heart.svg'), ('IGTV', 'igtv.svg'), ('LIKE', 'likee.svg'), ('REVO', 'record_voice.svg'), ('SAVE', 'save.svg'), ('SHOW', 'show.svg'), ('THUP', 'thumb-up.svg'), ('USER', 'user.svg'), ('USES', 'users.svg')], max_length=4, null=True, verbose_name='Картинка'),
        ),
    ]
