# Generated by Django 4.0.4 on 2022-06-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_alter_category_img_alter_subcategory_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Баланс')),
                ('operation', models.CharField(choices=[('R', 'Снятие'), ('A', 'Поступлениу')], default='A', max_length=1, verbose_name='Операция')),
                ('comment', models.CharField(blank=True, max_length=60, null=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balansh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
