# Generated by Django 4.0.4 on 2022-07-13 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_balancetransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_create'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='service',
            name='is_cancellation',
            field=models.BooleanField(default=False, verbose_name='Есть отмена?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INWOR', 'В работе'), ('NOPAY', 'Не оплачен'), ('BLOCK', 'Заблокирован'), ('COMPL', 'Выполнено'), ('CANC', 'Отменён'), ('WST', 'Ожидает'), ('WCL', 'Отменяется'), ('PART', 'Частично'), ('FAIL', 'Ошибка')], default='NOPAY', max_length=5, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('INWOR', 'В работе'), ('NOPAY', 'Не оплачен'), ('BLOCK', 'Заблокирован'), ('COMPL', 'Выполнено'), ('CANC', 'Отменён'), ('WST', 'Ожидает'), ('WCL', 'Отменяется'), ('PART', 'Частично'), ('FAIL', 'Ошибка')], default='NOPAY', max_length=5, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(default=0, verbose_name='Качество')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_site.order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='my_site.customerreview', verbose_name='Отзывы'),
        ),
    ]
