# Generated by Django 4.0.4 on 2022-07-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0007_alter_order_options_service_is_cancellation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='reviews',
        ),
        migrations.AddField(
            model_name='customerreview',
            name='service',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_site.service', verbose_name='Услуга'),
            preserve_default=False,
        ),
    ]
