# Generated by Django 4.0.4 on 2022-07-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_remove_service_reviews_customerreview_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_canceled_msg',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ошибка от провайдера'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_error_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
