# Generated by Django 5.1 on 2024-09-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0009_task_error_canceled_msg_task_is_error_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='quality',
        ),
        migrations.AddField(
            model_name='customerreview',
            name='rating_acc',
            field=models.CharField(default=('5', '5'), max_length=1, verbose_name='Качество аккаунтов'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='rating_speed',
            field=models.CharField(default=('5', '5'), max_length=1, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.CharField(choices=[('TEL', 'telegram.svg'), ('VK', 'vk.svg'), ('TIK', 'tiktok.svg'), ('YOTB', 'youtube.svg'), ('TWIT', 'twitter.svg'), ('OK', 'ok.svg'), ('INST', 'instagram.svg'), ('CLIN', 'c_link.svg'), ('STAR', 'c_star.svg'), ('EYE', 'eye.svg'), ('HEAR', 'heart.svg'), ('IGTV', 'igtv.svg'), ('LIKE', 'likee.svg'), ('REVO', 'record_voice.svg'), ('SAVE', 'save.svg'), ('SHOW', 'show.svg'), ('THUP', 'thumb-up.svg'), ('USER', 'user.svg'), ('USES', 'users.svg')], max_length=4, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='img',
            field=models.CharField(blank=True, choices=[('TEL', 'telegram.svg'), ('VK', 'vk.svg'), ('TIK', 'tiktok.svg'), ('YOTB', 'youtube.svg'), ('TWIT', 'twitter.svg'), ('OK', 'ok.svg'), ('INST', 'instagram.svg'), ('CLIN', 'c_link.svg'), ('STAR', 'c_star.svg'), ('EYE', 'eye.svg'), ('HEAR', 'heart.svg'), ('IGTV', 'igtv.svg'), ('LIKE', 'likee.svg'), ('REVO', 'record_voice.svg'), ('SAVE', 'save.svg'), ('SHOW', 'show.svg'), ('THUP', 'thumb-up.svg'), ('USER', 'user.svg'), ('USES', 'users.svg')], max_length=4, null=True, verbose_name='Картинка'),
        ),
    ]
