# Generated by Django 5.1 on 2024-09-12 16:50

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0010_remove_customerreview_quality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreview',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='my_site.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='rating_speed',
            field=models.CharField(default=('5', '5'), max_length=1, verbose_name='Скорость накрутки'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='my_site.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='service',
            name='text_info',
            field=ckeditor.fields.RichTextField(blank=True, max_length=700, null=True, verbose_name='Инфо'),
        ),
    ]
